package com.shamilov.core.android.ui.theme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF6750A4)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFE9DDFF)
val light_onPrimaryContainer = Color(0xFF22005D)
val light_secondary = Color(0xFF625B71)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFE8DEF8)
val light_onSecondaryContainer = Color(0xFF1E192B)
val light_tertiary = Color(0xFF7E5260)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFD9E3)
val light_onTertiaryContainer = Color(0xFF31101D)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1C1B1E)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1C1B1E)
val light_surfaceVariant = Color(0xFFE7E0EB)
val light_onSurfaceVariant = Color(0xFF49454E)
val light_outline = Color(0xFF7A757F)
val light_inverseOnSurface = Color(0xFFF4EFF4)
val light_inverseSurface = Color(0xFF313033)
val light_inversePrimary = Color(0xFFCFBCFF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF6750A4)
val light_outlineVariant = Color(0xFFCAC4CF)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFCFBCFF)
val dark_onPrimary = Color(0xFF381E72)
val dark_primaryContainer = Color(0xFF4F378A)
val dark_onPrimaryContainer = Color(0xFFE9DDFF)
val dark_secondary = Color(0xFFCBC2DB)
val dark_onSecondary = Color(0xFF332D41)
val dark_secondaryContainer = Color(0xFF4A4458)
val dark_onSecondaryContainer = Color(0xFFE8DEF8)
val dark_tertiary = Color(0xFFEFB8C8)
val dark_onTertiary = Color(0xFF4A2532)
val dark_tertiaryContainer = Color(0xFF633B48)
val dark_onTertiaryContainer = Color(0xFFFFD9E3)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1C1B1E)
val dark_onBackground = Color(0xFFE6E1E6)
val dark_surface = Color(0xFF1C1B1E)
val dark_onSurface = Color(0xFFE6E1E6)
val dark_surfaceVariant = Color(0xFF49454E)
val dark_onSurfaceVariant = Color(0xFFCAC4CF)
val dark_outline = Color(0xFF948F99)
val dark_inverseOnSurface = Color(0xFF1C1B1E)
val dark_inverseSurface = Color(0xFFE6E1E6)
val dark_inversePrimary = Color(0xFF6750A4)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFCFBCFF)
val dark_outlineVariant = Color(0xFF49454E)
val dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF6750A4)

internal val LightColors = lightColorScheme(
    primary = light_primary,
    onPrimary = light_onPrimary,
    primaryContainer = light_primaryContainer,
    onPrimaryContainer = light_onPrimaryContainer,
    secondary = light_secondary,
    onSecondary = light_onSecondary,
    secondaryContainer = light_secondaryContainer,
    onSecondaryContainer = light_onSecondaryContainer,
    tertiary = light_tertiary,
    onTertiary = light_onTertiary,
    tertiaryContainer = light_tertiaryContainer,
    onTertiaryContainer = light_onTertiaryContainer,
    error = light_error,
    errorContainer = light_errorContainer,
    onError = light_onError,
    onErrorContainer = light_onErrorContainer,
    background = light_background,
    onBackground = light_onBackground,
    surface = light_surface,
    onSurface = light_onSurface,
    surfaceVariant = light_surfaceVariant,
    onSurfaceVariant = light_onSurfaceVariant,
    outline = light_outline,
    inverseOnSurface = light_inverseOnSurface,
    inverseSurface = light_inverseSurface,
    inversePrimary = light_inversePrimary,
    surfaceTint = light_surfaceTint,
    outlineVariant = light_outlineVariant,
    scrim = light_scrim,
)

internal val DarkColors = darkColorScheme(
    primary = dark_primary,
    onPrimary = dark_onPrimary,
    primaryContainer = dark_primaryContainer,
    onPrimaryContainer = dark_onPrimaryContainer,
    secondary = dark_secondary,
    onSecondary = dark_onSecondary,
    secondaryContainer = dark_secondaryContainer,
    onSecondaryContainer = dark_onSecondaryContainer,
    tertiary = dark_tertiary,
    onTertiary = dark_onTertiary,
    tertiaryContainer = dark_tertiaryContainer,
    onTertiaryContainer = dark_onTertiaryContainer,
    error = dark_error,
    errorContainer = dark_errorContainer,
    onError = dark_onError,
    onErrorContainer = dark_onErrorContainer,
    background = dark_background,
    onBackground = dark_onBackground,
    surface = dark_surface,
    onSurface = dark_onSurface,
    surfaceVariant = dark_surfaceVariant,
    onSurfaceVariant = dark_onSurfaceVariant,
    outline = dark_outline,
    inverseOnSurface = dark_inverseOnSurface,
    inverseSurface = dark_inverseSurface,
    inversePrimary = dark_inversePrimary,
    surfaceTint = dark_surfaceTint,
    outlineVariant = dark_outlineVariant,
    scrim = dark_scrim,
)
